version: "3.9"
services: 
  client: 
    container_name: client
    image: client
    ports: 
      - 3000:3000 
    build:
      context: ./client 
    restart: always 
  api: 
    container_name: api  
    image: api 
    ports: 
      - 8000:8000 
    build: 
      context: ./api 
  admin:  
    container_name: admin  
    image: admin  
    ports: 
      - 5000:5000 
    build: 
      context: ./admin  